/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#022448",
        "primary-container": "#1e3a5f",
        "on-primary": "#ffffff",
        "on-primary-container": "#8aa4cf",
        "on-primary-fixed": "#001c3b",
        "on-primary-fixed-variant": "#2d486d",
        "primary-fixed": "#d5e3ff",
        "primary-fixed-dim": "#adc8f5",
        "secondary": "#555f70",
        "secondary-container": "#d6e0f4",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#5a6374",
        "on-secondary-fixed": "#121c2a",
        "on-secondary-fixed-variant": "#3e4757",
        "secondary-fixed": "#d9e3f7",
        "secondary-fixed-dim": "#bdc7da",
        "tertiary": "#361f00",
        "tertiary-container": "#533200",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#e39100",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "surface": "#f7f9fc",
        "surface-dim": "#d8dadd",
        "surface-bright": "#f7f9fc",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f7",
        "surface-container": "#eceef1",
        "surface-container-high": "#e6e8eb",
        "surface-container-highest": "#e0e3e6",
        "surface-variant": "#e0e3e6",
        "surface-tint": "#455f87",
        "on-surface": "#191c1e",
        "on-surface-variant": "#43474e",
        "on-background": "#191c1e",
        "background": "#f7f9fc",
        "outline": "#74777f",
        "outline-variant": "#c4c6cf",
        "inverse-surface": "#2d3133",
        "inverse-on-surface": "#eff1f4",
        "inverse-primary": "#adc8f5",
      },
      fontFamily: {
        headline: ["Manrope", "Noto Sans KR", "sans-serif"],
        body: ["Inter", "Noto Sans KR", "sans-serif"],
        label: ["Inter", "Noto Sans KR", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
